Repository javascript-tutorial/pt.javascript.info, pull requests merged in 2020-05, with the labels that each got.

#122 adding new article 12-nullish-coalescing-operator
  1-js/02-first-steps/12-nullish-coalescing-operator/article.md
Labels: needs +1

#125 Arrow Functions Revisited
  1-js/06-advanced-functions/12-arrow-functions/article.md
Labels: needs +1

#121 Export and import
  1-js/13-modules/02-import-export/article.md
Labels: needs +1, review needed

#127 Update folders.
  1-js/02-first-steps/05-types/article.md
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/solution.md
  1-js/02-first-steps/06-alert-prompt-confirm/1-simple-page/task.md
  1-js/02-first-steps/06-alert-prompt-confirm/article.md
  1-js/02-first-steps/07-type-conversions/1-primitive-conversions-questions/solution.md
  1-js/02-first-steps/07-type-conversions/1-primitive-conversions-questions/task.md
  1-js/02-first-steps/07-type-conversions/article.md
  1-js/02-first-steps/08-operators/1-increment-order/solution.md
  1-js/02-first-steps/08-operators/1-increment-order/task.md
  1-js/02-first-steps/08-operators/2-assignment-result/solution.md
  1-js/02-first-steps/08-operators/2-assignment-result/task.md
  1-js/02-first-steps/08-operators/article.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
  1-js/02-first-steps/09-comparison/article.md
  1-js/02-first-steps/13-while-for/1-loop-last-value/solution.md
  1-js/02-first-steps/13-while-for/1-loop-last-value/task.md
  1-js/02-first-steps/13-while-for/2-which-value-while/solution.md
  1-js/02-first-steps/13-while-for/2-which-value-while/task.md
  1-js/02-first-steps/13-while-for/3-which-value-for/solution.md
  1-js/02-first-steps/13-while-for/3-which-value-for/task.md
  1-js/02-first-steps/13-while-for/4-for-even/solution.md
  1-js/02-first-steps/13-while-for/4-for-even/task.md
  1-js/02-first-steps/13-while-for/5-replace-for-while/solution.md
  1-js/02-first-steps/13-while-for/5-replace-for-while/task.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/solution.md
  1-js/02-first-steps/13-while-for/6-repeat-until-correct/task.md
  1-js/02-first-steps/13-while-for/7-list-primes/solution.md
  1-js/02-first-steps/13-while-for/7-list-primes/task.md
  1-js/02-first-steps/13-while-for/article.md
  1-js/02-first-steps/14-switch/1-rewrite-switch-if-else/solution.md
  1-js/02-first-steps/14-switch/1-rewrite-switch-if-else/task.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/solution.md
  1-js/02-first-steps/14-switch/2-rewrite-if-switch/task.md
  1-js/02-first-steps/14-switch/article.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/solution.md
  1-js/02-first-steps/15-function-basics/1-if-else-required/task.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/solution.md
  1-js/02-first-steps/15-function-basics/2-rewrite-function-question-or/task.md
  1-js/02-first-steps/15-function-basics/3-min/solution.md
  1-js/02-first-steps/15-function-basics/3-min/task.md
  1-js/02-first-steps/15-function-basics/4-pow/solution.md
  1-js/02-first-steps/15-function-basics/4-pow/task.md
  1-js/02-first-steps/15-function-basics/article.md
  1-js/02-first-steps/15-function-basics/function_basics.png
  1-js/02-first-steps/15-function-basics/function_basics@2x.png
  1-js/02-first-steps/16-function-expressions/article.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/solution.md
  1-js/02-first-steps/17-arrow-functions-basics/1-rewrite-arrow/task.md
  1-js/02-first-steps/17-arrow-functions-basics/article.md
  1-js/02-first-steps/18-javascript-specials/article.md
Labels: review needed

#129 Fix object basics
  1-js/04-object-basics/02-object-copy/article.md
  1-js/04-object-basics/02-object-copy/variable-contains-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-reference.svg
  1-js/04-object-basics/02-object-copy/variable-copy-value.svg
  1-js/04-object-basics/03-garbage-collection/article.md
  1-js/04-object-basics/03-garbage-collection/family-delete-refs.svg
  1-js/04-object-basics/03-garbage-collection/family-no-family.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father-2.svg
  1-js/04-object-basics/03-garbage-collection/family-no-father.svg
  1-js/04-object-basics/03-garbage-collection/family.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-1.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-2.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-3.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-4.svg
  1-js/04-object-basics/03-garbage-collection/garbage-collection-5.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-admin.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john-lost.svg
  1-js/04-object-basics/03-garbage-collection/memory-user-john.svg
  1-js/04-object-basics/07-optional-chaining/article.md
  1-js/04-object-basics/08-symbol/article.md
  1-js/04-object-basics/09-object-toprimitive/article.md
Labels: review needed

#123 Global object
  1-js/06-advanced-functions/05-global-object/article.md
Labels: needs +1

#120 Promises chaining
  1-js/11-async/03-promise-chaining/01-then-vs-catch/solution.md
  1-js/11-async/03-promise-chaining/01-then-vs-catch/task.md
  1-js/11-async/03-promise-chaining/article.md
  1-js/11-async/03-promise-chaining/getMessage.js
  1-js/11-async/03-promise-chaining/head.html
  1-js/11-async/03-promise-chaining/promise-handler-variants.svg
  1-js/11-async/03-promise-chaining/promise-then-chain.svg
  1-js/11-async/03-promise-chaining/promise-then-many.svg
Labels: review needed

#132 Update 06-rest-parameters
  1-js/06-advanced-functions/02-rest-parameters-spread/article.md
Labels: review needed

#135 Fix miscellaneous
  1-js/99-js-misc/04-reference-type/2-check-syntax/solution.md
  1-js/99-js-misc/04-reference-type/2-check-syntax/task.md
  1-js/99-js-misc/04-reference-type/3-why-this/solution.md
  1-js/99-js-misc/04-reference-type/3-why-this/task.md
  1-js/99-js-misc/04-reference-type/article.md
  1-js/99-js-misc/05-bigint/article.md
Labels: review needed

#137 Update folder 2-ui/5/3-event-details
  2-ui/3-event-details/6-pointer-events/article.md
  2-ui/3-event-details/6-pointer-events/ball-2.view/index.html
  2-ui/3-event-details/6-pointer-events/ball.view/index.html
  2-ui/3-event-details/6-pointer-events/multitouch.view/index.html
  2-ui/3-event-details/6-pointer-events/slider.view/index.html
  2-ui/3-event-details/6-pointer-events/slider.view/style.css
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.md
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.view/index.html
  2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/task.md
  2-ui/3-event-details/7-keyboard-events/article.md
  2-ui/3-event-details/7-keyboard-events/german-layout.svg
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/index.html
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/script.js
  2-ui/3-event-details/7-keyboard-events/keyboard-dump.view/style.css
  2-ui/3-event-details/7-keyboard-events/us-layout.svg
Labels: review needed

#128 CSS-animations
  7-animation/2-css-animations/1-animate-logo-css/solution.md
  7-animation/2-css-animations/1-animate-logo-css/solution.view/index.html
  7-animation/2-css-animations/1-animate-logo-css/task.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/solution.md
  7-animation/2-css-animations/2-animate-logo-bezier-css/task.md
  7-animation/2-css-animations/3-animate-circle/task.md
  7-animation/2-css-animations/article.md
  7-animation/2-css-animations/boat.view/index.html
  7-animation/2-css-animations/boat.view/style.css
  7-animation/2-css-animations/digits-negative-delay.view/index.html
  7-animation/2-css-animations/digits.view/index.html
  7-animation/2-css-animations/step-end.view/index.html
  7-animation/2-css-animations/step.view/index.html
Labels: needs +1

#138 Update folder 2-ui/99-ui-misc
  2-ui/99-ui-misc/01-mutation-observer/article.md
  2-ui/99-ui-misc/02-selection-range/article.md
  2-ui/99-ui-misc/02-selection-range/range-example-p-2-b-3-range.svg
  2-ui/99-ui-misc/02-selection-range/selection-direction-backward.svg
  2-ui/99-ui-misc/02-selection-range/selection-direction-forward.svg
  2-ui/99-ui-misc/02-selection-range/selection-firefox.svg
  2-ui/99-ui-misc/03-event-loop/article.md
  2-ui/99-ui-misc/03-event-loop/eventLoop-full.svg
  2-ui/99-ui-misc/03-event-loop/eventLoop.svg
  2-ui/99-ui-misc/index.md
Labels: review needed

#142 Update network requests group
  5-network/01-fetch/01-fetch-users/_js.view/solution.js
  5-network/01-fetch/01-fetch-users/_js.view/source.js
  5-network/01-fetch/01-fetch-users/_js.view/test.js
  5-network/01-fetch/01-fetch-users/solution.md
  5-network/01-fetch/01-fetch-users/task.md
  5-network/01-fetch/article.md
  5-network/01-fetch/logo-fetch.svg
  5-network/01-fetch/post.view/server.js
  5-network/02-formdata/article.md
  5-network/02-formdata/post.view/server.js
  5-network/03-fetch-progress/article.md
  5-network/03-fetch-progress/logo-fetch.svg
  5-network/03-fetch-progress/progress.view/index.html
  5-network/03-fetch-progress/progress.view/long.txt
  5-network/04-fetch-abort/article.md
  5-network/04-fetch-abort/demo.view/server.js
  5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
  5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
  5-network/05-fetch-crossorigin/article.md
  5-network/05-fetch-crossorigin/cors-gmail-messages.svg
  5-network/05-fetch-crossorigin/xhr-another-domain.svg
  5-network/05-fetch-crossorigin/xhr-preflight.svg
  5-network/06-fetch-api/article.md
  5-network/06-fetch-api/logo-fetch.svg
  5-network/06-fetch-api/post.view/index.html
  5-network/06-fetch-api/post.view/server.js
  5-network/07-url/article.md
  5-network/07-url/url-object.svg
  5-network/08-xmlhttprequest/article.md
  5-network/08-xmlhttprequest/example.view/index.html
  5-network/08-xmlhttprequest/example.view/server.js
  5-network/08-xmlhttprequest/hello.txt
  5-network/08-xmlhttprequest/phones-async.view/index.html
  5-network/08-xmlhttprequest/phones-async.view/phones.json
  5-network/08-xmlhttprequest/phones-async.view/server.js
  5-network/08-xmlhttprequest/phones.json
  5-network/08-xmlhttprequest/phones.view/index.html
  5-network/08-xmlhttprequest/phones.view/phones.json
  5-network/08-xmlhttprequest/phones.view/server.js
  5-network/08-xmlhttprequest/post.view/index.html
  5-network/08-xmlhttprequest/post.view/server.js
  5-network/09-resume-upload/article.md
  5-network/09-resume-upload/upload-resume.view/index.html
  5-network/09-resume-upload/upload-resume.view/server.js
  5-network/09-resume-upload/upload-resume.view/uploader.js
  5-network/10-long-polling/long-polling.svg
  5-network/10-long-polling/longpoll.view/browser.js
  5-network/10-long-polling/longpoll.view/index.html
  5-network/10-long-polling/longpoll.view/server.js
  5-network/11-websocket/article.md
  5-network/11-websocket/chat.view/index.html
  5-network/11-websocket/chat.view/server.js
  5-network/11-websocket/demo.view/server.js
  5-network/11-websocket/websocket-handshake.svg
  5-network/12-server-sent-events/article.md
  5-network/12-server-sent-events/eventsource.view/index.html
  5-network/12-server-sent-events/eventsource.view/server.js
Labels: review needed

#145 Update repo
  10-misc/12-mutation-observer/article.md
  10-misc/index.md
  css.md
Labels: review needed
