Repository javascript-tutorial/pt.javascript.info, pull requests merged in 2023-12, with the labels that each got.

#408 Updates Object references and copying article
  1-js/04-object-basics/02-object-copy/article.md
Labels: review needed

#245 Comparisons
  1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
  1-js/02-first-steps/09-comparison/article.md
Labels: review needed

#405 Map and Set
  1-js/05-data-types/07-map-set/01-array-unique-map/_js.view/test.js
  1-js/05-data-types/07-map-set/01-array-unique-map/task.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/_js.view/test.js
  1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
  1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
  1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
  1-js/05-data-types/07-map-set/03-iterable-keys/task.md
  1-js/05-data-types/07-map-set/article.md
Labels: needs +1

#409 Symbol type
  1-js/04-object-basics/08-symbol/article.md
Labels: review needed

#248 Class basic syntax
  1-js/09-classes/01-class/1-rewrite-to-class/task.md
  1-js/09-classes/01-class/article.md
Labels: needs +1

#403 Attributes and properties
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/1-get-user-attribute/task.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/source.view/index.html
  2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/task.md
  2-ui/1-document/06-dom-attributes-and-properties/article.md
Labels: needs +1

#215 Polyfills and transpilers
  1-js/03-code-quality/06-polyfills/article.md
Labels: needs +1

#401 Logical operators
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
  1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/task.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
  1-js/02-first-steps/11-logical-operators/2-alert-or/task.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
  1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/task.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
  1-js/02-first-steps/11-logical-operators/4-alert-and/task.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
  1-js/02-first-steps/11-logical-operators/5-alert-and-or/task.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/solution.md
  1-js/02-first-steps/11-logical-operators/6-check-if-in-range/task.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/solution.md
  1-js/02-first-steps/11-logical-operators/7-check-if-out-range/task.md
  1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
  1-js/02-first-steps/11-logical-operators/8-if-question/task.md
  1-js/02-first-steps/11-logical-operators/9-check-login/solution.md
  1-js/02-first-steps/11-logical-operators/9-check-login/task.md
  1-js/02-first-steps/11-logical-operators/article.md
  images.yml
Labels: needs +1, review needed

#246 Conditional branching: if, '?'
  1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
  1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
  1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html
  1-js/02-first-steps/10-ifelse/2-check-standard/task.md
  1-js/02-first-steps/10-ifelse/3-sign/if_sign/index.html
  1-js/02-first-steps/10-ifelse/3-sign/solution.md
  1-js/02-first-steps/10-ifelse/3-sign/task.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
  1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/solution.md
  1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
  1-js/02-first-steps/10-ifelse/article.md
  images.yml
Labels: review needed

#274 Character classes
  9-regular-expressions/02-regexp-character-classes/article.md
  9-regular-expressions/02-regexp-character-classes/love-html5-classes.svg
  images.yml
Labels: needs +1

#410 Private and protected properties and methods
  1-js/09-classes/04-private-protected-properties-methods/article.md
Labels: needs +1
